version: "0.0.1"
services:
  postgresql:
    image: postgres:15.3
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - up-vibe-network
    container_name: postgresql

networks:
  up-vibe-network:
    external: true
