version: "3.8"

services:
  postgresql:
    image: ${POSTGRES_IMAGE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: up-vibe-dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "up-vibe-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - up-vibe-network
    container_name: postgresql

  liquibase:
    image: ${LIQUIBASE_IMAGE}
    volumes:
      - ./scripts/db/config:/liquibase/config/
      - ./scripts/db/changesets:/liquibase/changesets/
      - ./scripts/db/liquibase.properties:/liquibase/liquibase.properties
    command: --defaultsFile=liquibase.properties update
    networks:
      - up-vibe-network
    container_name: liquibase
    depends_on:
      postgresql:
        condition: service_healthy

  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    expose:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - up-vibe-network
    container_name: rabbitmq

  server:
    build:
      context: ${SERVER_CONTEXT}
      dockerfile: ${SERVER_DOCKERFILE_DEV}
    ports:
      - 3000:3000
      - 9229:9229
    expose:
      - 3000
      - 9229
    command: npm run dev:debug:docker
    container_name: server
    restart: always
    volumes:
      - ./server/logs:/usr/src/app/logs
      - ./server/config:/usr/src/app/config
      - ./storage:/usr/src/app/storage
      - ./server/src/sql:/usr/src/app/buildDebug/sql
      - ${SERVER_VOLUME_PLUGINS}:/usr/src/app/plugins
      - ./server/src:/usr/src/app/src
    depends_on:
      postgresql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    networks:
      - up-vibe-network

networks:
  up-vibe-network:
    name: up-vibe-network
