version: "3.8"

services:
  postgresql:
    image: postgres:15.3
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: up-vibe-dev
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "up-vibe-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - up-vibe-network
    container_name: postgresql

  liquibase:
    image: liquibase/liquibase:4.23
    volumes:
      - ./scripts/db/config/db.changelog-0.0.1.xml:/liquibase/db.changelog-0.0.1.xml
      - ./scripts/db/changesets/:/liquibase/changesets/
      - ./scripts/db/liquibase.properties:/liquibase/liquibase.properties
    command: --changeLogFile=db.changelog-0.0.1.xml --url=jdbc:postgresql://postgresql/up-vibe-dev --username=admin --password=admin update
    networks:
      - up-vibe-network
    container_name: liquibase
    depends_on: 
      postgresql:
        condition: service_healthy

  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./server/logs:/opt/app/logs
      - ./server/config:/opt/app/config
      - ./storage:/opt/app/storage
    restart: always
    command: npm run dev:docker
    container_name: backend
    expose:
      - 3000
    depends_on: 
      postgresql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully

networks:
  up-vibe-network:
    name: viv
