version: "3.8"

services:
  server-app:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./server/logs:/opt/app/logs
      - ./server/config:/opt/app/config
      - ./storage:/opt/app/storage
    restart: always
    command: npm run dev:docker
    container_name: app-server
    expose:
      - "3000"
      - "9229"

volumes:
  ignore:
