version: "3.8"

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "up-vibe-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - up-vibe-network
    container_name: postgresql

  liquibase:
    image: ${LIQUIBASE_IMAGE}
    volumes:
      - ${LIQUIBASE_VOLUME_CONFIG}:/liquibase/config/
      - ${LIQUIBASE_VOLUME_CHANGESETS}:/liquibase/changesets/
      - ${LIQUIBASE_VOLUME_PROPERTIES}:/liquibase/liquibase.properties
    command: --defaultsFile=liquibase.properties update
    networks:
      - up-vibe-network
    container_name: liquibase
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    expose:
      - ${RABBITMQ_PORT}
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - up-vibe-network
    container_name: rabbitmq

  server:
    build:
      context: ${SERVER_CONTEXT}
      dockerfile: ${SERVER_DOCKERFILE}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_INSPECT_PORT}:${SERVER_INSPECT_PORT}
    expose:
      - ${SERVER_PORT}
      - ${SERVER_INSPECT_PORT}
    command: ${SERVER_COMMAND_RUN}
    container_name: server
    restart: always
    volumes:
      - ${SERVER_VOLUME_LOGS}:/opt/app/logs
      - ${SERVER_VOLUME_CONFIG}:/opt/app/config
      - ${SERVER_VOLUME_STORAGE}:/opt/app/storage
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    networks:
      - up-vibe-network

networks:
  up-vibe-network:
    name: up-vibe-network
