version: "3.8"

services:
  postgresql:
    image: postgres:15.3
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: up-vibe-dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "up-vibe-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - up-vibe-network
    container_name: postgresql

  liquibase:
    image: liquibase/liquibase:4.23
    volumes:
      - ./scripts/db/config:/liquibase/config/
      - ./scripts/db/changesets:/liquibase/changesets/
      - ./scripts/db/liquibase.properties:/liquibase/liquibase.properties
    command: --defaultsFile=liquibase.properties update
    networks:
      - up-vibe-network
    container_name: liquibase
    depends_on:
      postgresql:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.12.2-management
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - up-vibe-network
    container_name: rabbitmq

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    expose:
      - 3000
      - 9229
    command: npm run dev:debug:docker
    container_name: server
    restart: always
    volumes:
      - ./server/logs:/usr/src/app/logs
      - ./server/config:/usr/src/app/config
      - ./storage:/usr/src/app/storage
      - ./server/src/sql:/usr/src/app/buildDebug/sql
      - ${SERVER_VOLUME_PLUGINS}:/usr/src/app/plugins
      - ./server/src:/usr/src/app/src
    depends_on:
      postgresql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    environment:
      - DEBUG="*"
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$3000/up-vibe/v1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - up-vibe-network
    user: root

networks:
  up-vibe-network:
    name: up-vibe-network
