version: "3.8"

services:
  build-server:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./dist:/opt/app/dist
    command: npm run build
    container_name: build-server
