version: "0.0.1"
services:
  rabbitmq:
    image: rabbitmq:3.12.2-management
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ../../volumes/rabbitmq:/var/lib/rabbitmq
    networks:
      - up-vibe-network
    container_name: rabbitmq

networks:
  up-vibe-network:
    external: true
