name: ci-debug
run-name: CI Debug
on:
  pull_request:
    branches:
    - integration
  push:
    branches:
    - integration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build container
        run: docker build .
        working-directory: server
  check-database:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Update docker compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && run sudo chmod +x /usr/local/bin/docker-compose

      - name: Print docker compose version
        run: docker-compose --version
      - name: Run liquibase
        run: docker-compose -f docker-compose.yml up liquibase
