name: ci-debug
run-name: CI Debug
on:
  pull_request:
    branches:
    - integration
  push:
    branches:
    - integration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build container
        run: docker build .
        working-directory: server
  check-database:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run liquibase
        run: docker-compose -f docker-compose.yml up liquibase
