name: Create and publish a Docker image to GitHub Packages

on:
  push:
    branches:
      - 'release/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: server-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/up-vibe/server
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ steps.server-meta.outputs.tags }}
          labels: ${{ steps.server-meta.outputs.labels }}

  build-and-push-file-coordinator-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: services-file-coordinator-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/up-vibe/services/file-coordinator
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker file-coordinator image
        uses: docker/build-push-action@v5
        with:
          context: ./services/file-coordinator
          push: true
          tags: ${{ steps.services-file-coordinator-meta.outputs.tags }}
          labels: ${{ steps.services-file-coordinator-meta.outputs.labels }}

